sudo: false
language: ruby
rvm:
- '2.4'
- '2.5'
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
before_install: gem install bundler -v 1.16.2
deploy:
  provider: rubygems
  api_key:
    secure: PfSSb9W/fL+lIhszRWJuHx9X3wDNpMOlfqfAusX3FXdW0zfIDfa6M7aUn45HVujODWujj/WTwYwTJLoi8WggPxHQp4Ov59IiddXkuGEr51CyiCwvidMYLZcZxt98Ah9AkVDHYX+RrqncwdWenuXGQ0tb5dtG0Qs5BOFWYIVjJWD0wNroQsjbk0K6L5/jFccQA3wHdUJUs8LiGSxYtK4prjMzBT+fQFYTgG7N/hT1CjiuuiozqsGQfCagvVuGF8c5Sur27NgZtP3qPampuETK112zcC3IEnhhjQAsn3Tqg98to1ZS37Q4H6PdvqE4KxvnP4T4ZsBts2tdVQ+KVR27M/rSlNiedGBk0WpGf/3rjP8bV3ow3Z5LVTBiHHOZVrdBSVHFD6Cpb7NOeup1WB49HiraDy7yRH/s68wm6Be+WndomB8jCqWArJpyJaHAgyccDPc8+dpIT/+PBs1p1UYzp1+R/HdMCuSMUovTUBO/Hd5rn1glJenCCeyb3UKOjOn1PYwyf2+Z/aH6VWeD1Geiom/dZNj2q/ewVvEK2DY8gwOpj5t/TgpMZ0eUt9haQQvi5XDYoPjNBbVvBksEt5fb3tAssvxAC/qN5VMMEUeOxdz+OiIXNp8ZXLSfCUQxc96+Zs6hKN53/fdi+QvurO42opHKGX49B16m+slTnW9A4h8=
  on:
    tags: true
    rvm: "2.4"
