sudo: false
language: ruby
rvm:
- '2.4'
- '2.5'
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
before_install: gem install bundler -v 1.16.2
deploy:
  provider: rubygems
  gem: k8s-client
  api_key:
    secure: BeCL7YnYqG/2sQK5TZtLcvHO33TEToT+bMVK5y4YezdgazvsnAhs5KoqA3AtcCyXsBZpcN1dT2OpDbLZYIgw1rFW11qHVsgDdQOpWDOR0NdG+cv2MylBDRRUXA5KgyOWfu4CGrp9xHKexX/oUhXfF165pINazu8adNon5KTvhmW2iCC29TPI32iY+DkTp2hXJXKSsWAgn2ZTKUUfsOxcROzfiiakpLuxxLFOIvF10GpTYSmld21AQUqQKIJqz4RipwO/vOXg/bF3N82F398uV06Uch+rfvHbv4bY1ElTFuO/MiTj9QoCsDaAKzrh+mzMRJjcfos7zPiZT679S8myxxq3LvIvw9SPTju4y3o5eU3fI5hZ6LXrKvF1VREu17MPOoxRzVC4l2R3qsEIGULZ/hSYIiViEiaxbFaU9wpd4GEGFMbnkE8/XX1PkJ/PYV3zNvBxMIoqhH1tEjqdYOvNbN5Ie7qVHmmmiknuqr4LyBYz5v0nwOCnBYfSvYGE3Wa1KDeImexVH5UWyyerGKdYeG6h7uAZirQVmedH1Ddr3qFtR0mmTPTydWahBdcvfxtrZbOrVioDoRgghE5tCS28p2mapiS2Bq4no4ycW3Ta7IBC4AyA9U9QL/MT6BOhnkX3unwW1V91kTFWG1yJmBThWp/kZCaKSAVld/STxtQ5iIM=
  on:
    tags: true
    rvm: '2.4'
