sudo: false
language: ruby
rvm:
- '2.4'
- '2.5'
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
before_install: gem install bundler -v 1.16.2
deploy:
  provider: rubygems
  gem: k8s-client
  api_key:
    secure: ArI9RehHbuJIZklO3FA0cGp4WOc2QYkO26BsKZDWLkTOpRo0GSQRt4WMeOmVpdYfR7yNRgyV8eaGnEYr6ZNS8ejjmwWUnRhBaoEzEC4e9RxaDPTVJDpFOPi38eAtUyAZ7bMeJzhgPev7Y7ofrymuVmsXq/48mJZtSHJckii0UYjaveiH8aGeXxCVFY1csexN36AYr3NCkCqQp9ICXAhQI+UXftVKoN/uXMJC2l8VgjRuxn61x68/XCAxoPr44kYY4PSDAF9eYX/2UTDx4Vu4g4CzCCEC8vYQ36peuFGiCt5lzAIZdu07Xotch6rpHpRRGAhiahNrZVc3oma2IWkPmAJgPWHjjXraq5gjB1O3avLNmmH3rZOPl6kv/FGmafrfu4IbNx78V+SLMWu8+m98xbBLDk/wphtfQuMHAF1huQS0lsKZ2G58OYd7SyJL9RibhOZXgSC4D5YU1uT1m1wIpTw1e7aNkHiSR+zmhmhhKXFW1lJhDsHYQ6prIpKFTkrxChRX4dOyF0ua/hDJP5PdniPEe2ANcao6giEhB5Sr/IdHgFoIiQ1dwuDW6UiNgkLyGAgLVlH61Ie3BBUf8faPs36bgrgwmG5s7/9fF8w892m+Ho+Xx0vSGpup8L64ew9xgrjnW4cLcFUesaVyG+t8uPequosf+wHd8fi9r7KF+PQ=
  on:
    tags: true
    rvm: '2.4'
